kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare-amd64-binaries
    image: ubuntu:20.04
    commands:
    - apt-get -y update && apt-get -y install make curl tar docker.io
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $(pwd)
    - make check-security
    - make k8s-binaries
    privileged: true
    volumes:
    - name: socket
      path: /var/run/docker.sock
    when:
      event:
        - tag
        - pull_request

  - name: publish-hyperkube-linux-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-linux-amd64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: prepare-arm64-binaries
    image: ubuntu:20.04
    commands:
    - apt-get -y update && apt-get -y install make curl tar docker.io
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $(pwd)
    - make check-security
    - make ARCH=arm64 k8s-binaries
    privileged: true
    volumes:
    - name: socket
      path: /var/run/docker.sock
    when:
      event:
        - tag
        - pull_request

  - name: publish-hyperkube-linux-arm64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-linux-arm64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
depends_on:
- linux-amd64
- linux-arm64
